### ISSUE TITLE
szavazomotor funkciok

### ISSUE THREAD

**Issue by utopszkij** [edemo/adadocs#10]
server to server remote call funkciok
----------
addquestion (title, description,requedassurance, voteenabled) result: questionid
addoption(questionid,title,description) result: optionid
editquestion(questionid,title,description, requedassurance,voteenabled)
editoption(optionid(optionid,title,description)
delquestion(questionid)
deloption(optionid)
getquestion(questionid) result json question+options
getvotercount(questionid,assurance) return integer
getvokscount(quetionid,assuranc) return integer
getcondorce(questionid, assurance) return: json condoce lista
setvoksweight(questionid, userproxiid)
       - likvidhez kell, utolag megadom a korábban leadott szavazat sulyát (hány embert képvisel)
getvotes(questionid) result json tételes lista a nyilt szavazatokrol)

user browser send form data
------
sendvoks (questionid, pref.sorrend, publicvote, redirectURL) result: nyiltan szavazott y/n
delvoks(questionid,redirectURL)
getmyvoks(questionid, redirectURL) result json

a sendvoks formon lehet olyan chkbox, hogy a szavazó nyiltan szavaz.

**Comment by magwas** [comment]
Ok, figyelembe veszem, szólok ha valamit másképpen kéne.

**Comment by magwas** [comment]
setvoksweight nincs, és néhány dologhoz teljesen más az interfész, de a többi funkcionalitás ránézésre megvan:
http://adadocs.demokracia.rulez.org/engine/#10173398-9767-4620-bb65-c2511d8eda73

**Comment by utopszkij** [comment]
Azt látom nagyjából milyen funkciók vannak, ez rendben is van (egyenlőre 
félre téve a likvid demokrácia funkciót).

Sajnos az én szellemi képességeimet az meghaladja, hogy ebből az 
anyagból én megértsem a pontos hívási szintaxist és a híváshoz megadanó 
adatok pontos szintaxisát és szemantikáját valamint  a visszakapott 
információk szintaxisát és szemantikáját.

Azt kell, hogy kérjem, hogy számomra ezt egyszerűbben, ha lehet magyarul 
és példákkal ilusztrálva írjátok le, ha azt akarjátok, hogy használjam 
ezt a szavazó motort. :(

Tibor



2017. 01. 02. 21:03 keltezéssel, Árpád Magosányi írta:

**Comment by utopszkij** [comment]
Nem látom a leadott szavazat törlésének a lehetőségét.
Továbbá kell olyan funkció is amivel a GUI app le tudja kérdezni, hogy agy szavazáson hány szavazásra jogosult user van (hány regisztrált usernek van a szükséges assurance -ja). Ez az olyan jellegű funkciókhoz kell mint "érvényes a szavazás vagy nemérvényes", "az ötletet elegen támogatják-e ahoz, hogy megvitatásra szavazásra kerüljön".
