### ISSUE TITLE
sso anchor UI

### ISSUE THREAD

**Issue by krosza** [edemo/adadocs#3]
Jó lenne ha az sso anchornak lenne egy user barát egyszerű szöveges felülete, ahol tájékoztatnánk usert t arról hogy:

Ez egy Titkos Kód előállító  "gép".

A gép által előállított Titkos Kód  tulajdonosa az  az személy lesz  aki a titkos kód előállításához használt adatok jogos személyes tulajdonosa, függetlenül attól, hogy ki állította elő.

- az itt beírt infók nem kerülnek sehol sem rögzítésre,
- a rendszer az elkészített titkos kódokat sem őrzi meg,
- azt a célt szolgálja, hogy bárki elő tudjon állítani egy Titkos Kódot, amit az ADA használ,
- az itt előállított titkos kódra vigyázzon, ne adja meg senkinek azon kívül, hogy beírja az ADA megfelelő mezőjébe
- a  felhasználandó  személyes adatait  pontosan rögzítse, mert különben a későbbiekben nem fogja tudni igazolni, hogy ön a jogos tulajdonosa a titkos kódnak,
- az ADA ezt a rendszer  is használja a tanúsításhoz
 

 Jó lenne kitalálni egy nevet a cuccnak,  pl "Titkos Kód Gép"

**Comment by magwas** [comment]
fb csoprtban kérdés, szavazás a névre.
